name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run Python script
        run: |
          python -m pip install python-dotenv
          python -m pip install python-telegram-bot 
          python automate.py
        env:
          TELEGRAMTOKEN: ${{ secrets.TELEGRAMTOKEN }}